### ISSUE TITLE
preg_replace error (php7.3+)

### ISSUE THREAD

**Issue by 1271** [bavix/router#9]
`bavix\router\src\Router\Route.php:13`

Replace:
`protected $defaultRegex = '[\w-А-ЯЁа-яё]+';`
To:
`protected $defaultRegex = '[\w\-А-ЯЁа-яё]+';`

You need to escape the dash.

**Comment by rez1dent3** [comment]
@1271 I think you're using ~1.0. Upgrade to ~2.0

**Comment by 1271** [comment]
Thx.
